#!/bin/bash
function usage {
cat <<USAGE
 USAGE: retainer <source data dir> <git repository dir>

  Append the contents of <source data dir> to the record retained in the Git
  repository directory. Useful for aggregating logs, mail and other multfile,
  append-only collections of data.

USAGE
}

function chgit {
  source_directory="$1"
  git_archive_data="$2"
  shift ; shift
  git --git-dir="$(readlink -f "$git_archive_data")" \
      --work-tree="$(readlink -f "$source_directory")" "$@"
}

function retain {
  chgit "$1" "$2" add .
  if chgit "$1" "$2" status --porcelain | egrep -q '^[MACR]'
  then
    echo 'Files were found to append; committing.' 1>&2
    chgit "$1" "$2" commit -m "${3-Retained by script.}"
  else
    echo 'No changes; skipping commit.' 1>&2
  fi
}


if fgrep -q 0f64f693-7761-4552-9698-a5d961540886 "$0"
then
  set -o errexit -o nounset -o pipefail
  for arg in "$@"
  do
    case "$arg" in
      -h|'-?'|--help)           usage ; exit ;;
    esac
  done
  retain "$1" "$2"
fi

